version: '3'
 
services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: traccar
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "6033:3306"
    volumes:
      - ./dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

  traccar:
    image: traccar/traccar
    hostname: traccar
    restart: always
    ports:
      - "5000-5150:5000-5150"
      - "8082:8082"
    volumes:
      - traccar-db:/opt/traccar/data/database
      - ./conf/traccar.xml:/opt/traccar/conf/traccar.xml

volumes:
  traccar-db:
  dbdata:
